apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-secret
  namespace: homarr
spec:
  encryptedData:
    SECRET_ENCRYPTION_KEY: AgAj3IdJXJGaliSAPRVEOZjL5NnZdQb1EpWTFGKA8si0hujjdN5dwKMoWHefHJxqxGxyJy6dncWN0UIMmIsX6oZr4RC5g1WSQiZYypCddoeR4DLAcDOLG8SsSMMltDejaGcwbebOOpGBJ+TnW3w5HektZ+kfzOkBtdgq9bH2pxKUZUSOqlIb5AbFX0koE2HZGv8EUnfF7JTaUDIq8L4eWFuLQJZAyB4SH7iEVgVQGWTcPbJQ/f8RVXBA5oY76c2Ss2tNGM9wZcOmpTCwQjs6+ymAd4GEsA5Gz5N8EA8WJjlxu40O5tLqwtVfVJjI30oZsBVM19vqp5rg+viU3VIsMW19ViJF0+Q2PUO3HnGeg1Q/L0PQGn3vi2jCWxCimd1MbQtl77n3z/SEpuwpHQzo1Q1OWdavu0RM9RSXOFKM7nLcozC4+OfsHofGx89ObTj66W7G9IZsi7Xu7WDEi+4i1I8RSmME9VhI+nQDOTetaDYTyybNbpLWcKkNdywru8LcY87WjQUxPd9ZBZ4BofzsQ/3dLibE5OVtHIJDIgdICcwzcFF5rSUW28xG/KUgDfi7h/qW+KiZoOFTjpXxB/iAPKlYeD+2nNpAWoM/8ZS00ceXlkCHbgdMP7PhsJeTXuJur5TJS98hN6ZZOfrqoHS2fJZAB0e0P6uMwQxzgtRnAQzsWRXCW66gotg5GEBVFXp3EojVc6I1S8/OkcSzWneHubnULs3wGULjo6JQIqvtrXpKqqPviSeCoLwaMy33bAyLVg3sruEZHRnx61BamqwYtP2G
  template:
    metadata:
      name: homarr-secret
      namespace: homarr
