---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCmywMYLrS1MMccKdy2MVdJIr+R51oMIANRt2cg+PVwRlL6YjTjNpv0k4J0tvTbnuYcdBVOb7obJxSDz4DUU4mqK+PsNe2ZJZbRujpQtQmaZUegtw+rf8WIlSEGKbMlpHf/oPVi9JHmSufLK6LRrFjA1u2Bi1LiQV97NUYZVTvdP5QsPp1cbYTmBDoZ581cfQ2/RMb5xyXVR8yWm+/58XxP62MBrPsCGJ6q3HJy8ArTu8JICDNq14l0HLQhnP4DNd+YqweUR6GkMXe6BhMUzmg+18//fYLOUUAqEMaETn3C61lLsXFvzWrI3a0tASn0RlkJXpvXA/wjkRMM2DUE0qOFv+yDXXl6eB4eNA02N3Iqe7UO6y8MsLYH8ne6Wni2Z+0+dp6q7hocJWQzD0/uSZhJvGuPfGhfxmv+wbWHVoG3PQIFL2S1rH4l30k+KtTAEi5adsTKgF1/Af8m9CV321Dl17VQUi6pEG9e4pZwpfhi8sIUKxsbTgeLpf5eOaAM9rp3Uj2Swf3ebKBbWd759WsOVkjQ6OoTqGfPRlhW3kgLAyem0/REptaMf9CiF1YVrCZOMiG7ByIZRwal3jtHKGuy58JSOT4WodlqeNaOYPheo1frJhCvdEpQGffSgvLN/QDhh6iKaPMLRhp16lBLsAvEglO83Eu1aHtfgS2fzkepmFSD5rvmg9ExUXLjEGEoWoD7fIUD33hKn54=
    admin-user: AgCuMsUOHkqH51Nt7lk7PEOGlYh7QNPIojoV+ll5xUykpkwSZrB0Y/6asxBV6MPpovLQbKGc9l3VF7xLGt2v7O369xuU/+DHFUL+0d2t6rTn9WhUzUIlaLW3pS6ZpgboPK6ed7YpyWTJ89+nBxDquD+Gy81UD2VYeaDsdQR602rNOW1bfru7Up1t/lkMLdUJh7teNNzb9L4CEpkcuWXbUTd2DVgwL1tgpylo0oQ0IO3KjJ+b9jVuDG239nqEDod+2tI1u81L+K/MMUhhcd3bLbtx1U6fSm03oG1ReZUhFEyyXtcQUNG32FYTGXm7t4nHWnET2Lt1+BNoofXHAy585jV8culyvcCnt1C5Pb8jFrKwJklyZPtNHAdo1fQ9Kv3B3d9SjKRN8NKLCYkTDPe/8HKRJKjGJ9vDPhwAhRWjWcXmMMPj22z7BlD/j8RUbzjXhZ55UNmYDEq0vcEtT9UUihNwk72jEJKBVYGj18UBPqZCEjtf8nnbUVqWA80zhNuWbXYPpJAkbxrfRwgjRI7l3Y7dL0/fOXFvEh3tMnkt1t+7HK25lQ8p4gY3hqQcYSu34zXT6LAWfxPGCGb/r9iA5uXvpWYxVfIozZNA5R3ffdoZeEAf9zELrYk04M2e3VuBH7HFrqW7F2CWcRcVJCKWdKuJnSm+XL9K/vxAF7AuOAkBlz+W0e1wfG4cIDKOJYgZZS9k630Osw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
