---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC8CVjrbV0clTuLmZwMTdzJa3Oq4vdXYk2FIFiaHlp090jT40K3e836x5Xr8FIKLyJUTTp+WPDfH0MV6xvJ3gO+4xDQDsT8/ZS6SSvMckFLaCtWTVgvfahW1Q//Y4n3wTpYL0wB+pMhpWhuuYh4KPAQ8Nryzd7tecI8r3UH6iA3H1qTOUsgmc7nGSHZT6BSzdztAbpJ0I5Rc59HJOz5OGIBvUH0atY/7Dqdl9AsKuErRddcI9JfhoSAcM4oX/eF5ryqbBdNLilC2qz8XFLCuFgXn+9JTXYmbPzhPrvjLePiTiedFiarvRi10roLTUWJ+Vi0ZJJhxyZfnyVxM6KxRVUaKW9COTDM4dDTi2ltHgu8CTyWSjqlTzEcCSFiHGjGIWCdVrR3fLbWKMEPyFmd+sguRo2QwIfEv/MqgH5IZnqjQa3t3V9HIOgOtD+xZASoypz+Fe8ZDZrKAWtlv7ExKXFs+cGK4DUkKnDN0JhfyW6GgOhBaxNr7J2SF5tuqkkyztzQAdBXhjTqVJ1VS9J5aIalxe8zxK7N7xOdOtNedLekt1caKl1PjJzaKslMRXSdVZtxOfbofgTbzPLAxe4/EkBWZdq5JzbGaSDWkf+FiN95+pu1xT18ZYcBtKIOxcE7IzZawnjLNP1kjoZEgcJmH8ujgRqpqBn3IUk1+5bkvhjrW/twZU4eJWUEFr9F4rp1NbgVLlowXRWPyYHo
    admin-user: AgB1PUDC+uMcV8kz5q4hnaakPKDwLjbJEo6hVyPrXqlUV08QEjVWofi7YO1qv2UsAJLuDUwMRU0h0R4Al1SGBCSKvgWeag9ZAqWpLR9iqx43Ae+2jjIjvgqDr1jai1B45OPCBZViTNueiQXLHMNsPSy87I2x321yCOnSuFWBfjk533tlm8FSWyPZklk4EWiEL5gCyQmNZ2zorINy9AHOlrAvSJYQuZ1zfaaop75RIFVzcumbr3grE1po1/KeQic3UeEYUg5wGSKykfZ2zHNMNWfsaOh5dx+5P6Lxo7cc3CH+YAnHuE9ldw6VTo9J4+3UzBXfnS31+aYTGGCyU8WPEvSo6wJlLniePtt+seoOjgGCyYp8NSLmFTG5BoRiCeyzIRv90Fz6Qxn9xyck2/CMy95P4fpwtiDSBkV7CX3XFMsdBshpw+PVXtPHRVnPB/jFFYpAnBjL1DDYCmrdzdjoNE5LvDd1sg9FtXHs342nUSYUTz/Ur9/KngFLiF7BuWdz1bZh3bZeyAvzoG6R770/tQFyg++AauokYTgilx9P4fDERijDr9wRwB6fuhjkqtqiBJixCnVv6gR2HtQ7kID6EfzeMJSCe/0ihdU6U4/i+NTpgoAIzH6w4+hNSQPZHz0Iy8IDjKPsss8X2iXl03wDv4oyzEmTRrXbCJ+Y2tAlJvVTiSuJ7tghWpW+v3Vr2TaMYYVmwbkjIQ==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
