apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCn7MK+mXiIuG0Z3/tS59iw2oke8JewEt2SiSkZ5hZEkOY2C/D7BfCptR/WLmHpQaO5GBC+XzDNTn8lwQ5CO5jv5b4hBTKJiWDy3XmgtIiJjogB3qwZ2cma39iZN3/u6bOnBTgISRPkl9l7F3beIK29fyz02vNgxnR7FXcV83yo8B0TUFdVv4iJn3k+GU2vx0IlAhRQI1r14x56tmOLCWrDS6f0VOWWJvgxUsg0ty4i+r8UqAqWS3LTsg7BeIZvn6wOwgolqbLVLVMgWRk0eU9NJlrGvOjUTA0xgxoY/QuH9dEGQlaP5DIe0N78ZV2EoLAZsqI2Gw6bGegEqtn/3+MApanxc/wNmg404sapjV127N7xpp7GZXaJaJ/i6b4C0v2lT91TiYhN76FBpy020ukKFYVFjgdbigOX/vamI7DJR0dmqAMsbfo8mcTRCtUY07zkavxBvokxatgE44JOkeZ/ieU+V5d83C4poKNXI7DjcygCEbE3bp8TPE0qT/Y4g5NZPNBbVzRUY7gwnjaHB5Ov1go2PEE7VrekZTz5VZw1heusLSL3ivt4pJG1x4XxFQ1rXhbBIXukYCwcM1RhI7iX4BAq8/7IFxgg2IwMtWcUKZ2VDrjA+QmNYjFMS7M7dyzCS9UaiTy/zbaC9R1Wn4I+WvtZNdHKm1yKW67JoWwd5iW7ZdtteaLW9VPVJ9USyVgj9MgyteqADFC/g6d7dcBcDBU0/XPujLB/3q5dMx64hp9QOlqFw8RDSXo2soedAqpxjDSxZiWeX7o3GRaGhwvk
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
