---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    db_password: AgAjT4iPSt66IBc4Ip4g/zGvjBD2wCJeREUTDYWA3w49DgL5NWwBoGdLtCERW4u8cvej555JNwwNffISW72Ry6oB+UFUupziCGq93V8mOUUVg3APw1A9HCVKiRtX/6ZiXbyjh4JlEwjc7RtiYhBqOoj4DHQmgU1BOY9XuYlGQdFv/0nLe/E7BJN+JUXaJaz/Ut2WAIHps5N7ecw5HY6LJJtYKrzswapvOHXerP+0mv+K1aRllJQPA7G0s2MmaynzxXYwkpG0wEqSpzVE3jqQabEof8LuZOepPViqvnXgaRb0SW2ZCNFeD6Q+oKUdolrHvUrTWe3tizk3lTuSNgC3VnRZuoDn6a8yQJizvcbbvH922rOix51ZvKI7hLzWPC8xZBe/J4f8UCKnnTxv8acqSuSzrS/CNOSB1a42408+EdGM+MKAJtlC6T1PNaMWumuTDWceEZv8TjCwldAZ3lVRxa02Duc4g+eQWs/cQo/YDl5iNx4YCRFgPZXcmOvsHppwKUXPDiuDM0Q3SKSM9IAw0T4sDh9gIRz3oRnDVPgygkgLrA+cLzwTMKnPIiabTHoGf2Gu6fQpHmctkSsxMJlDrGf2YK/mwAQOwNRPeCNKHuQpzLUskxQpyK9wfKFcZ0P7cC+CWfnD9bOra0QHh4w2YAkXAtbp58y+3XvLT+csR5n0SNVdOKMYFhx4cXa4IN5GZBH44qcOkMSe/1PY0eCuy8WE6IKmlQ==
    encryption_key: AgC5qXNTuRu8rU41CqYh0123m1ctqRPRTZiNwG7Kc5XGPN78Xd09Jlt3GeTqRhlOHXls6UZaZlRm7Vk8opXfHhEbBnfq/XymFZRMY0GBRzM4tn5dSb6DFJP37yK3bD85AOLxtiXTqocmil1Kgw5VP/b9Y3m4OMQFlIsN0nr3mCIbRT7j4MeeTFDSV2DjSc6FHRMC22hcXAvTLkfCx3C72UH2p+jQYY1z6RwubTDqkcjAccEOupu+HlrEPyTlwF9rANyotstR+PQcOAeqoRlH7a5gCZIqQFMF8igWkvOnvlmGFTAD4ICrQh0ylu2qF4ZAvfgewfu+fezcK0XKsyE2c58uC0gT03f4zByKUmB3tv+VIYx0jfVPZLvJlCAoQ5+YPhg51QYfRAHCx3p4cI2CmHjNgFU+y5D1rJ6f3qVCgyBVBzSdl8k2QBAn1C7R2hpgW8d27QUZM8aBuxeSmL/EgxjWZH4MKnfsRMPICaa+79p9rUs9gaZy1+phYBVL8xtlbGUU5dHsfkbsCvrQyXOeHIvh0n3r9UK0Dmvvx8+vXxOH8EXPIfSr72Zrp2/b4Yl5lP363BLMvRenIByjfM2MpHxEYZyM5TPAF4qdl+K36dzRsrjL/cQEIfgi+CGi/UJqDU1Qye5YaHIw6AHa+qYlWpeeszeEG4TZWQYk3ynhkkxoksHd4uHOZpOUq85AOfUFpl5xx/URzRUdh/NqkJXvQLUttcTAd7256h1H7zdmlBjcPw==
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
