---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCOWzz77QCtnJdMnDJ30KsZqnv322IGyo6sjzQ0kssB02b1Yf3TsGX77sCB5Zh5mQALP6hmMYFkBzBcazylSJGRVC5NB2P7kmHIvNaxhggpfK0IrO7wc/lr7swq4CAnbh1ub7IwaxNIVANSokeyxYkkCHBQp/FKaMUQD9S15fuWpuSw30WrrST5mDQSFAr1slG474eiEkUW5cRwwyhIXuZb0VP5F54YNkqxRsgelHBHUX7riHMr3goCf0twMo8zyew0r6RsqKpv39iQb6vqK1zlfejuU3XNB3K/QQb57cdKnmZzqiJAUBUrlNE5ewZb0KDkBVI803iXRM2oobcQHigMtCYZol6lYawmvY4GS2wBD6LMm1BEJka8YrUfg2xeIZ60WgXzJCLL2H0aZeYh9gufMt1ikS5HLfdQvnPoYzqomB5f4U9DLxQpmM7tylxtiOL5PLkJzYWTgStmLCHMquZFSZDYOMH6Wl//TabMLNa1AYVrezkc5wOstTGBITOm6eLIHe1KIK37G+2wVMgq1Mt0PuahwgxhC/e5b/Gm/trcmNbQeIgA+LwbHoxiGdeqE2Fuwuw2Scf7NhlgMmz7V4J8PPpHJxuTjM2MW7H6vi9aQFyuNjuGOif/mz6gJKHpsRK3p24c9f0m1XeMPi7Et4n2Hy2gs/PRtBzyCUUel3+FMklc40WWgCJ+3XAlyURxp6fpwORbbtf+IgVt
    admin-user: AgAnb9CoOeqQfY8w1qjI1Z8SikCJPDkxfks7yJlkKvhNIGTBasMOm7B00aQ2m7Pyr2VTYFuMT2TlZJjjRj6viZ6zuM2gh48p9LrmRpNa9SDeoB3YQPyyXKZ7BQaLGr11XWZEadeMiDIG6aj/FBztvij0u179vOMNsYAgbwcVb9lCCJY5snGsffL1qjyJ0SIE3VGvszwQ0eYD6vL53EibMm+teyeLcYr+oMaaQDe7UDqQdoVfJ95kbmXUheeTGsKu33C60YuPqqy6PmCYnvX5Cmt3ItFTFEpRz332KCTVFGzOQpEyNW0Xm+awahdUjvU63aMJ7FiYSgyo5Bsc7h6J7c4rApJTzlcy6XeP6x46ucOJ6dJ2AYjTusK/NzDSDxyvq6UpCG3C9xLLGHCx0p7l9hARGYRIhM5CYOeKELzriWToyx7Jvk3PE6JFXVNLh4csUX3a/dkj4fnaHmtyn4QY23rTgZ4nwi4fgOSXeH/H2ZUt+FrYArm+C0lWJcHYOhzuOJ5lMRRzwA5YKiTY6+Hy8Hb6w0GG3ljoXcLtxGsvlwUVhcRNbWatEXKgqeOq1otyChh+DBm8zhGA9ac4QxX8Be/YIalom0iL/3kVRF0RwtAY5RnSAnrE6gqEPhdiAo/ebsdZcmj4DwGYlUI0rl0PljzlyyftpvHqN+braM+2MZkNkujbLuT4rxn7ptdrce8Imrya2kmfkw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
