---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBxVgrPTB/BSBFq0yX3pc1DWG0luYiU6hlXUyYLWtpDITqEiHIsT/aE2Ecj2O3k+uoCtJ/7y2VoTBpUj7WLOlLLJCeViAa6AJabjwiraR7UDxMTQLaw43zE1keBZPSG2SHgdqJeoSGpRIKtHStn89yad/XH5v+X8haYmkkFqFmXYte6DxRfdDNXB4E3xlVSbnFrB3Q7ZS1S4SJpypeacO8z3WXfRho1gDGYvD8tPw0YPWGT3oRBgd8cL8/xnOl92MHFGMhIjXOdsuk/029CD3guzhfXKdh/qGbXH5ckFlbK0h3ZQH5J8prSyg+LuKzsj0B9NknzlcUrR26Rq8WHEnAdSOSq39/cHx4PsJy2efoGzl3cC2kpPTad7rrb1jGB0lgFKPRg+xqoN4qbfDgrhZqB9O+Pn9vsn2jmVQkOOWSU9fcLrD2yzGsSu7XIevGZJRLbJ3Flis0OAaAi6CiIzy+CGcX9yeP0pkAEboU4iYD+AGxcekdEhxYmr0biCGF4OtiLDfDe8mduhhvmeQL73LF1SfH/QODHgaI8v910Jcs6p/tKnSqYuZTYRF3cWDw99MyZA0krzBYpAZ43MlzCAU4XHGDIAdwZdBhVQRpujlHkxXx3p4ugsxsdn+jOPAvum1jr9sdLJCNj/qCWHEfOWMeVPNp8zGKMySgOcfOk2XXocFruhho/3jbkrokK3xvIT4Q9mQbJrUYeww==
    admin-user: AgBtjfdMAxBLy4Dt2oB+vsu9U9xsLtEJttPysTP45YgQQ4rjPO4L1XWXEhgm/DiGouFDY+18cQQzFWKbKhkXmaOMtsQvIfLVp01VgJ2CpsGFr2ONZd4im0ARoT7PkzFVrYChiEv5SeG8KBASAZ18+rxY+a1ApPStzQVrKxUxDDLxiTGR3mjxJZ7owMn8vqN1Pa/0SgdB6oKkvgVx86BKL7PmaK81oJND/HtG8exw3tSWz0PHM5DJ3Yf5erQ6cMxu11zR4pw7WlN5WhPJggjlOWnyIWxJqwmzd8XE5RtmmqrABtqG6HPe5n+IrcrRETnmlitTCOLT+svxfwgCnYyJgwqg2+Vb14CQ5LNpkXUDk5KLGzUDZhq+6BgF+be/DCbCoMHaCXrga3fLq45R/9Z3DqY7fO1QESMm9MvOG2NJXq86CecKtDB40goBMPAxS0Uu08G/FNoE/emLXRSMlYjWTLQXuLaX/oZtwRs/wVbdzBv4S7D39OvcYfz6Gai0XSeucV+aqp+lQkG5OK2knFG/MQXRA1sdu8/Fn72whcbPKTDaRHqHvjX7zgWi3MOLZwyLunu43SxtwspPzgo08RceVXJY0AIT5oe6EaeFYekH96eqywyMYU6myZ4FdTGXbQfVj5z06gx3ZyMYk19mMeWNQ45IMhniYvOM6CGT+RSQdjRS8gc1h0ax1dH5GVQSZpJ59nyBP6VnHg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
